[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/landscape-client-72
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.7    unsupported  01:44:55Z

App               Version          Status   Scale  Charm             Channel      Rev  Exposed  Message
landscape-client                   waiting    0/1  landscape-client  latest/edge   72  no       agent initialising
mysql             8.0.41-0ubun...  active       1  mysql             8.0/edge     378  no       
mysql-router      8.0.41-0ubun...  waiting      1  mysql-router                     0  no       Waiting for mysql app on backend-database endpoint
mysql-test-app    0.0.2            waiting      1  mysql-test-app    latest/edge   73  no       
ubuntu-advantage                   active       1  ubuntu-advantage  latest/edge  145  no       Attached (esm-apps,esm-infra)

Unit                   Workload  Agent       Machine  Public address  Ports           Message
mysql-test-app/0*      waiting   idle        0        10.88.192.113                   
  landscape-client/0*  waiting   allocating           10.88.192.113                   agent initialising
  mysql-router/0*      error     idle                 10.88.192.113                   hook failed: "backend-database-relation-changed"
  ubuntu-advantage/0*  active    idle                 10.88.192.113                   Attached (esm-apps,esm-infra)
mysql/0*               active    idle        1        10.88.192.186   3306,33060/tcp  Primary

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.88.192.113  juju-6234cb-0  ubuntu@22.04      Running
1        started  10.88.192.186  juju-6234cb-1  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:42:48 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:42:48 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:42:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-0: 01:42:53 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
unit-ubuntu-advantage-0: 01:42:53 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 127
machine-1: 01:43:49 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:43:49 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:43:49 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-0: 01:44:51 ERROR unit.mysql-router/0.juju-log backend-database:8: Failed to run MySQL Shell script:
import json
import mysqlsh
import traceback

try:
    # Disable wizards in this script, since it will be invoked without --no-wizard
    shell.options.set('useWizards', False)
    session.run_sql("DROP USER IF EXISTS `relation-8_5a191c4f9026481-9`")

except mysqlsh.DBError as exception:
    error = {
        "message": str(exception),
        "code": exception.code,
        "traceback_message": "".join(traceback.format_exception(exception)),
    }
else:
    error = None
with open("/tmp/mysqlsh_error.json", "w") as file:
    json.dump(error, file)

stderr:
[31mERROR: [0mFailed to retrieve the password: Process "mysql_config_editor" finished with exit code 1: mysql_config_editor: Can't create/write to file '/root/snap/charmed-mysql/139/.mylogin.cnf' (OS errno 13 - Permission denied)
couldn't create the login file : Permission denied
mysql_config_editor: Error on close of '<fd out of range>' (OS errno 9 - Bad file descriptor)
operation failed. : Bad file descriptor
MySQL Error 2005: No such host is known ''

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/snap.py", line 263, in _run_command
    output = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri', 'relation-8_5a191c4f9026481@:3306', '--python', '--file', '/tmp/mysqlsh_script.py']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/mysql_shell/__init__.py", line 74, in _run_code
    self._container.run_mysql_shell(
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/container.py", line 212, in run_mysql_shell
    return self._run_command(args, timeout=timeout, input=input)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/snap.py", line 272, in _run_command
    raise container.CalledProcessError(
container.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri', 'relation-8_5a191c4f9026481@:3306', '--python', '--file', '/tmp/mysqlsh_script.py']' returned non-zero exit status 1.
unit-mysql-router-0: 01:44:51 ERROR unit.mysql-router/0.juju-log backend-database:8: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/snap.py", line 263, in _run_command
    output = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri', 'relation-8_5a191c4f9026481@:3306', '--python', '--file', '/tmp/mysqlsh_script.py']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/charm.py", line 235, in <module>
    ops.main.main(MachineSubordinateRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/venv/lib/python3.10/site-packages/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 3141, in _on_relation_changed_event
    getattr(self.on, "database_created").emit(
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/abstract_charm.py", line 344, in reconcile
    self._database_provides.reconcile_users(
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/relations/database_providers_wrapper.py", line 77, in reconcile_users
    self._database_provides.reconcile_users(
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/relations/database_provides.py", line 306, in reconcile_users
    relation.create_database_and_user(
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/relations/database_provides.py", line 123, in create_database_and_user
    shell.delete_user(username, must_exist=False)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/mysql_shell/__init__.py", line 207, in delete_user
    self._run_sql([statement])
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/mysql_shell/__init__.py", line 113, in _run_sql
    self._run_code(
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/mysql_shell/__init__.py", line 74, in _run_code
    self._container.run_mysql_shell(
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/container.py", line 212, in run_mysql_shell
    return self._run_command(args, timeout=timeout, input=input)
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-0/charm/src/snap.py", line 272, in _run_command
    raise container.CalledProcessError(
container.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--passwords-from-stdin', '--uri', 'relation-8_5a191c4f9026481@:3306', '--python', '--file', '/tmp/mysqlsh_script.py']' returned non-zero exit status 1.
unit-mysql-router-0: 01:44:51 ERROR juju.worker.uniter.operation hook "backend-database-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...